build:
  nodes:
      tests:
        override:
          - js-scrutinizer-run
          - export JWT_SECRET="L0ngS3cr3tK3y!"
          - export PORT="1337"
          - chmod +x db/reset_test_db.bash
          - npm test
            coverage:
              file: coverage/clover.xml
              format: clover
            idle_timeout: 1800